import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from './_components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fama competitons',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-full ">
      <Navbar/>
       <main className='flex flex-col flex-1 h-full pt-20 '>
   
      {children}
      
       
       </main>
        
        
        </body>
    </html>
  )
}
