export const metadata = {
  title: "Admin ",
  description: "Generated by Next.js",
};

import "../../globals.css";
import Navbar from "./_components/navbar";
import Sidebar from "./_components/sidebar";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-full flex-row    flex  ">
      <Sidebar />

      {/* */}
      <main className=" flex flex-col   w-full overflow-y-scroll">
        <div className="min-h-10 bg-white">
          <Navbar />
        </div>
        <div className="h-full  overflow-scroll p-10">{children}</div>
      </main>
    </div>
  );
}
